#!/bin/bash

# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"m"

### BACKGROUND ###
BK_BLACK=$ESC_SEQ"48;5;16m"

### MAJOR COLORS ###
COL_RED=$ESC_SEQ"38;5;09;01m"
COL_GREEN=$ESC_SEQ"38;5;10;01m"
COL_PURPLE=$ESC_SEQ"38;5;57;01m"
COL_BLUE=$ESC_SEQ"38;5;27;01m"
COL_MAGENTA=$ESC_SEQ"38;5;13;01m"
COL_CYAN=$ESC_SEQ"38;5;14;01m"
COL_ORANGE=$ESC_SEQ"38;5;208;01m"
COL_CHERRY=$ESC_SEQ"38;5;124;01m"
COL_FORREST=$ESC_SEQ"38;5;22;01m"
COL_WHITE=$ESC_SEQ"38;5;231;01m"

### MINOR COLORS ###
COL_MRED=$ESC_SEQ"38;5;09;02m"
COL_MGREEN=$ESC_SEQ"38;5;34;02m"
COL_MPURPLE=$ESC_SEQ"38;5;57;02m"
COL_MBLUE=$ESC_SEQ"38;5;27;02m"
COL_MMAGENTA=$ESC_SEQ"38;5;13;02m"
COL_MCYAN=$ESC_SEQ"38;5;14;02m"
COL_MORANGE=$ESC_SEQ"38;5;208;02m"
COL_MCHERRY=$ESC_SEQ"38;5;124;02m"
COL_MFORREST=$ESC_SEQ"38;5;22;02m"
COL_MWHITE=$ESC_SEQ"38;5;231;02m"

### START EXAMPLE COLOR ###
#echo -e "\x1b[38;5;{COLORID};01m TEXT  \x1b[m"
### END EXAMPLE COLOR ###

function bashcolors(){
echo -e "$BK_BLACK
$COL_RED \$COL_RED         $COL_MRED \$COL_MRED
$COL_GREEN \$COL_GREEN     $COL_MGREEN \$COL_MGREEN
$COL_PURPLE \$COL_PURPLE   $COL_MPURPLE \$COL_MPURPLE
$COL_BLUE \$COL_BLUE       $COL_MBLUE \$COL_MBLUE
$COL_MAGENTA \$COL_MAGENTA $COL_MMAGENTA \$COL_MMAGENTA
$COL_CYAN \$COL_CYAN       $COL_MCYAN \$COL_MCYAN
$COL_ORANGE \$COL_ORANGE   $COL_MORANGE \$COL_MORANGE
$COL_CHERRY \$COL_CHERRY   $COL_MCHERRY \$COL_MCHERRY
$COL_FORREST \$COL_FORREST $COL_MFORREST \$COL_MFORREST
$COL_WHITE \$COL_WHITE     $COL_MWHITE \$COL_MWHITE
$COL_RESET"
}

function wpshell(){
clear
echo -e "
Type$COL_CYAN wpshell$COL_MGREEN to return to this menu:                         
  $COL_CYAN wpReplaceCore $COL_MGREEN  - Scan for WP Version and Backup/Replace Core Files
  $COL_CYAN coreLatest $COL_MGREEN     - Backup/Replace WP Core Files With Latest Version
  $COL_CYAN dbexport $COL_MGREEN       - Export WP Database
  $COL_RESET"
}

function wpReplaceCore(){
version=$(grep 'wp_version ' wp-includes/version.php | cut -d\' -f 2)

echo -e "$COL_GREEN\rReplacing existing core with fresh $version files\n$COL_RESET"

if [[ ! -e "wordpress-$version.tar.gz" ]]; then
	if ! wget -q "https://wordpress.org/wordpress-$version.tar.gz"; then
		echo -e "$COL_RED\rUnable to download wordpress-$version.tar.gz $COL_RESET"
		return 9
	else echo "Downloaded wordpress-$version.tar.gz..."
	fi
else echo "wordpress-$version.tar.gz already exists! Please rename!"
return 1
fi

temp=$(date -u +"%Y_%m_%d-%H_%M")

echo "Checking for existing WordPress files..."
local wpfiles=$(find -maxdepth 1 -name "wp-*" -o -name index.php -o -name license.txt -o -name readme.html -o -name xmlrpc.php)

if [[ -z "$wpfiles" ]]; then
	echo -e "No existing WordPress files found..."
	else
	oldWP="WPSHELL_CORE_$temp"
	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
	mkdir "$oldWP"
	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
fi

tar -xf "wordpress-$version.tar.gz" --strip-components=1 && echo "Unpacking the update..."
rm -f "wordpress-$version.tar.gz" ### && echo "Removed wordpress-$version.tar.gz..."

if [[ -d "$oldWP/wp-content" ]]; then
	mv wp-content wp-content_"$temp" ### && echo "Moved default wp-content to wp-content_$temp..." &&
	mv "$oldWP/wp-content" . ###  && echo "Moved old wp-content back into place..." &&
	rm -rf wp-content_"$temp" ### && echo "Removed wp-content_$temp..."
fi

if [[ -f "$oldWP/wp-config.php" ]]; then
	cp "$oldWP/wp-config.php" .
 	### echo -e "Copied old wp-config.php back into place..."
	echo -e "$COL_GREEN\rSuccess:$COL_RESET Core replaced with stock $version files"
	else
	cp wp-config-sample.php wp-config.php
	echo -e "$COL_CYAN\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
fi
echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
wp --skip-plugins --skip-themes core update-db --quiet
}

### WGET LATEST ###
function coreLatest() {
###  version=$(grep 'wp_version ' wp-includes/version.php | cut -d\' -f 2)

echo -e "$COL_GREEN\rReplacing existing core with latest version\n$COL_RESET"

if [[ ! -e "wordpress-$wpver.tar.gz" ]]; then
	if ! wget -q "https://wordpress.org/wordpress-latest.tar.gz"; then
		echo -e "$COL_RED\rUnable to download wordpress-latest.tar.gz $COL_RESET"
		return 9
	else echo "Downloaded wordpress-latest.tar.gz..."
	fi
else echo "wordpress-latest.tar.gz already exists! Please rename!"
return 1
fi

temp=$(date -u +"%Y_%m_%d-%H_%M")

echo "Checking for existing WordPress files..."
local wpfiles=$(find -maxdepth 1 -name "wp-*" -o -name index.php -o -name license.txt -o -name readme.html -o -name xmlrpc.php)

if [[ -z "$wpfiles" ]]; then
	echo -e "No existing WordPress files found..."
	else
	oldWP="WPSHELL_CORE_$temp"
	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
	mkdir "$oldWP"
	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
fi

tar -xf "wordpress-latest.tar.gz" --strip-components=1 && echo "Unpacking the update..."
rm -f "wordpress-latest.tar.gz" ### && echo "Removed wordpress-latest.tar.gz..."

if [[ -d "$oldWP/wp-content" ]]; then
	mv wp-content wp-content_"$temp"  ### && echo "Moved default wp-content to wp-content_$temp..." &&
	mv "$oldWP/wp-content" .  ### && echo "Moved old wp-content back into place..." &&
	rm -rf wp-content_"$temp" ### && echo "Removed wp-content_$temp..."
fi

if [[ -f "$oldWP/wp-config.php" ]]; then
	cp "$oldWP/wp-config.php" .
	### echo -e "Copied old wp-config.php back into place..."
	echo -e "$COL_GREEN\rSuccess:$COL_RESET Core updated to latest version"
	else
	cp wp-config-sample.php wp-config.php
	echo -e "$COL_CYAN\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
fi
echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
wp --skip-plugins --skip-themes core update-db --quiet
}

### EXPORT DATABASE ###
function dbexport(){
# Get info from the wp globals
getWPinfo

echo "Starting export..."
file="$2"
[[ -z "$file" ]] && file="WPSHELL_$dbname"_$(now).sql
mysqldump -h "$dbhost" -u "$dbuser" -p"$dbpass" "$dbname" > "$file" && echo -e "Exported database '$dbname' to file '$file'\n" || echo -e "Failed to export database '$dbname' to file '$file'!\n"
}

########## BACKEND FUNCTIONS ##########
function getWPinfo(){
# Get info from the wp globals
dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ;
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ;
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ;
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;')

# Alternatly read in vars from wp-config.php
#read -r dbhost dbname dbpass dbuser dbprefix <<< $(cat wp-config.php | egrep "^[^/].*[\"']DB_(NAME|USER|PASSWORD|HOST[^_])|table_prefix" | sort -d | sed "s/.*[\"']\(.*\)[\"'].*;.*/\1/" )
}
